[package]
name = "danker69/fusion"
description = "A fork of Elttob's modern reactive UI library, built specifically for Roblox and Luau"
license = "MIT"
authors = ["Elttob"]
version = "0.2.0-beta"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

include = ["src", "wally.toml", "wally.lock"]
exclude = ["**"]

[dependencies]
